### ISSUE TITLE
Telegramm-Duplizierung im Tunnelmodus

### ISSUE THREAD

**Issue by Ing-Dom** [OpenKNX/OAM-IP-Router#1]
vor 11 Tagen
Haben die Ursache von Roberts Problem gefunden.
Da ist wohl noch eine Rückkopplung der Telegramme, die werden ja dann per Routing auch weitergeleitet (wenn auf weiterleiten eingestellt) und das führt dazu, dass das selbe Telegramm nochmal mit HopCount=5 im Tunnel auftaucht...
@Ing-Dom (Dominik)
hast du auf die schnelle ne Idee warum das Routing nochmal iwie den Eingang des Telegrams triggert oder so?
25 Antworten
  vor 11 Tagen
kannst du mir das ggf etwas detailierter beschreiben?
richtung des telegramms, wo kommts rein / geht aus, broadcast, unicast, multicast etc..
  vor 11 Tagen
Die #09:63 ist die erste korrekte Antwort, vom Geräte. Also TP->IP
Danach kommt das Routing Indication Telegram. Soweit korrekt.
Danach wird die Antwort aber nochmal gesendet mit einem verringerten HopCount #09:64
![image](https://github.com/OpenKNX/OAM-IP-Router/assets/12643772/168b5611-3ef0-4fb1-907b-fba78eb318e8)
  vor 11 Tagen
Sobald man physikalisch Adressierte Telegramme filtert, ist das Problem weg.
  vor 11 Tagen
es kommt also ein unicast telegram von der tp linie an den tunnel? und der router sendet es zusätzlch per routing?
  vor 11 Tagen
Und danach kommt es nochmal per Tunneling mit HopCount=5
  vor 11 Tagen
das erste senden ist korrekt, sofern die einstellung für unicast TP>>IP auf "weiterleiten" steht
  vor 11 Tagen
Das erste ist ja Tunneling: korrekt
Das zweite Routing: korrekt da weiterleiten drin war
Das dritte ist falsch: da HopCounter geringer
  vor 11 Tagen
ok, verstanden. wo klinkst du dich mit dem tunnel ein für eingehende pakete?
  vor 11 Tagen
Das frameReceived vom DataLinkLayer
  vor 11 Tagen
https://github.com/Ing-Dom/knx/blob/rp2040_eth_tunneling/src/knx/data_link_layer.cpp#L116
data_link_layer.cpp

    _cemiServer->dataIndicationToTunnel(frame);

<https://github.com/Ing-Dom/knx|Ing-Dom/knx>Ing-Dom/knx | Hinzugefügt von GitHub
  vor 11 Tagen
das sollte ok sein,
ABER:
du rufst dataIndicationToTunnel auch im sendTelegram https://github.com/Ing-Dom/knx/blob/rp2040_eth_tunneling/src/knx/data_link_layer.cpp#L195und wenn der network layer das tp telegramm bekommt und beschließt ich muss das routen ruft er ja die sendtelegram vom (ip)datalinklayer auf.
data_link_layer.cpp

    _cemiServer->dataIndicationToTunnel(tmpFrame);

<https://github.com/Ing-Dom/knx|Ing-Dom/knx>Ing-Dom/knx | Hinzugefügt von GitHub
  vor 11 Tagen
und dann haste es doppelt
  vor 11 Tagen
mit hop-count -1 weil es war ja schon geroutet
  vor 11 Tagen
Ah okay. das kommt tatsächlich nicht von mir. Das war schon vorher drin für das USB ding.
  vor 11 Tagen
bzw sogar für rf... https://github.com/Ing-Dom/knx/blob/master/src/knx/data_link_layer.cpp#L156
  vor 11 Tagen
ich denke auch dass man es ggf braucht
  vor 11 Tagen
z.B. wenn der router selbst der sender ist
  vor 11 Tagen
Dann müsste man das iwie abfragbar machen
  vor 11 Tagen
wie wäre mit einem
pseudocode:

 if(src.addr == ownaddr) 
     _cemiServer->dataIndicationToTunnel(tmpFrame);

  vor 11 Tagen
Theoretisch müsste ich ja abfragen, ob der Empfänger eine Tunnel Adresse ist.
Wenn ja, muss das Telegramm ja auch nicht auf TP.
  vor 11 Tagen
stimmt bei unicast sind sender und empfänger genau bekannt

**Comment by thewhobox** [comment]
Duplizierung ist behoben und wurde auch schon getestet.
Kann somit denke ich geschlossen werden.

**Comment by Ing-Dom** [comment]
fixed with https://github.com/OpenKNX/knx/commit/c1623faf6df222d15d7d2590fc5f395bdc838faa

Den Bug schließe ich erst wenn es ein Release mit dem Bugfix gibt. Mache ich bald.
