### ISSUE TITLE
Unable to download personal address

### ISSUE THREAD

**Issue by colinheru** [OpenKNX/OAM-IP-Router#15]
![image](https://github.com/user-attachments/assets/8dabdff4-e3ee-4804-90e7-c3daf347359f)

![image](https://github.com/user-attachments/assets/06f7e761-2a73-4021-a4b7-cb89b7c3bb09)

ETS prompts that more than one device is in programming mode。Looking forward to your reply, thank you！

**Comment by Ing-Dom** [comment]
what interface did you use for programming?
please make a screenshot of Monitor while trying to program

**Comment by colinheru** [comment]
It is caused by Schneider's IP routing. It has been solved, thank you!
![image](https://github.com/user-attachments/assets/3df9f199-759d-4d2e-a8e8-cdb1fbd773c1)
