### ISSUE TITLE
NAT-Modus der ETS funktioniert nicht

### ISSUE THREAD

**Issue by mumpf** [OpenKNX/OAM-IP-Router#6]
Wenn man in der ETS den NAT-Modus aktiviert (manuelle Konfiguration der Schnittstelle), dann funtionert die Tunneverbindung nicht mehr.
![image](https://github.com/OpenKNX/OAM-IP-Router/assets/14316138/b4e736bc-62b4-4769-82fd-f935e9c13e5b)

Gruß, Waldemar

**Comment by thewhobox** [comment]
Laut Spec 3/8/2 wird beim ConnectRequest die IP im HPAI auf 0.0.0.0 gesetzt. Dies signalisiert, dass die IP vom UDP Sender verwendet werden soll.
Ist hier die angegeben IP 0 https://github.com/OpenKNX/knx/blob/rp2040_ip_routing/src/knx/ip_data_link_layer.cpp#L382 sollte diese IP https://github.com/OpenKNX/knx/blob/rp2040_ip_routing/src/rp2040_arduino_platform.h#L106 verwendet werden.

**Comment by Ing-Dom** [comment]
![image](https://github.com/OpenKNX/OAM-IP-Router/assets/12643772/758f9b97-a3cf-4441-a490-5adbd76f2d8b)

**Comment by Ing-Dom** [comment]
könnte mit 0.1.2 / 2.12.2 gefixt sein, bitte nachtesten

**Comment by thewhobox** [comment]
![image](https://github.com/OpenKNX/OAM-IP-Router/assets/45664417/2db11a92-124c-4a51-8fdc-282e46fe5418)
Konnte es auf die schnelle nur lokal testen, da tut es aber, was es soll.
