### ISSUE TITLE
Update über ETS

### ISSUE THREAD

**Issue by Joeknx** [OpenKNX/OAM-IP-Router#7]
Wenn ich die neuste Version der Applikation lade und in die ETS importiere, bekomme ich keine zweite Applikation im Katalog angezeigt. Es bleibt bei 2.12 oder 0.1.
Wurde die neue Versionsnummer in der neuen Version vielleicht vergessen?

Und ist ein Update über die ETS überhaupt möglich?

**Comment by Ing-Dom** [comment]
das ist korrekt, das Update ist ein reiner Firmware-Patch 0.1.0 auf 0.1**.1** bzw. 2.12**.1**.
Die ETS Applikation hat sich nicht geändert.
FW-Update über ETS ist bei OpenKNX nicht vorgesehen.
FW-Updates erfolgen über USB mit der mitgelieferten Ladedatei oder per https://github.com/OpenKNX/KnxFileTransferClient über Bus.
